### PR TITLE
Add NewConnectionFromConnString and fix session issues

### LINKED ISSUE #20: chdb-go with --path file did not persist the table data and it messed up display on my MacBook for some reason
Thank you folks for the great `chdb`.
I'm playing with the `chdb-go` CLI first to get familiar with the functionality. However, I found persistence not working no matter how I gave the file path (absolute, relative) or whether I created `chdb.db` file ahead of time or not. Not sure why.

Also the display was messed up after `exit` and can only be recovered by `reset`. I'm using MacOS's Terminal.

Any ideas to fix these or work around it? Thanks!

### PR DESCRIPTION
**Pull request by auxten**
Fix #20

### CODE REVIEW

**Comment by auxten** [comment]
@agoncear-mwb Please help me review that.

**Comment by auxten** [comment]
@wudidapaopao FYI

File: chdb-purego/binding.go [hunk 1]
```diff
@@ -39,7 +39,7 @@ var (
 	freeResult    func(result *local_result)
 	queryStableV2 func(argc int, argv []string) *local_result_v2
 	freeResultV2  func(result *local_result_v2)
-	connectChdb   func(argc int, argv []string) **chdb_conn
+	connectChdb   func(argc int, argv []*byte) **chdb_conn
```
Comment (agoncear-mwb) [inline chdb-purego/binding.go:42]: is this needed? in theory purego will automatically convert types.

File: chdb-purego/chdb.go [hunk 2]
```diff
@@ -141,12 +146,76 @@ func (c *connection) Ready() bool {
...
+	c_argv := make([]*byte, len(new_argv))
+	for i, str := range new_argv {
+		// Convert string to []byte and append null terminator
+		bytes := append([]byte(str), 0)
+		// Use &bytes[0] to get pointer to first byte
+		c_argv[i] = &bytes[0]
+	}
+
+	// debug print new_argv
+	for _, arg := range new_argv {
```
Comment (agoncear-mwb) [inline chdb-purego/chdb.go]: should remove the debug log

File: chdb-purego/binding.go (hunk 1 above)
Comment (auxten) [reply chdb-purego/binding.go:42]: Yes, if not this way. Extra argv not work.😅

**Review by agoncear-mwb — CHANGES_REQUESTED** [review]

File: chdb-purego/binding.go (hunk 1 above)
Comment (agoncear-mwb) [reply chdb-purego/binding.go:42]: ok, lgtm

**Review by agoncear-mwb — APPROVED** [review]
